### ISSUE TITLE
Modify hmcluster and change the value of disable from false to true. This will not stop the component from running, which is not as expected.

### ISSUE THREAD

**Issue by FloatXD** [hwameistor/hwameistor-operator#217]
Modify hmcluster and change the value of disable from false to true. This will not stop the component from running, which is not as expected.
```
  evictor:
    disable: true
    evictor:
      image:
        registry: ghcr.io
        repository: hwameistor/evictor
        tag: v0.13.0
    replicas: 1
```
