### ISSUE TITLE
Missing the list permission for daemonset

### ISSUE THREAD

**Issue by FloatXD** [hwameistor/hwameistor-operator#351]
![Image](https://github.com/user-attachments/assets/006a9bb3-d71b-46b4-9695-dc6687564b8e)
```
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  verbs:
  - get
```
